"""init

Revision ID: 705b297bb31c
Revises: 
Create Date: 2022-06-27 03:26:42.507743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '705b297bb31c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopunits',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('parentId', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('OFFER', 'CATEGORY', name='shopunittype'), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parentId'], ['shopunits.id'], name='shopunits_parentId_fkey'),
    sa.PrimaryKeyConstraint('id', name='shopunits_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopunits')
    # ### end Alembic commands ###
